spring:
  profiles:
    include: oauth

  session:
    store-type: jdbc

  datasource:
#    url: jdbc:h2:tcp://localhost/~/levelupboard;MODE=MySQL
    url: jdbc:h2:mem:testdb;MODE=MySQL
    username: sa
    passwrod:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
#        show_sql: true
        format_sql: true
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect

logging.level:
  org.hibernate.SQL: debug
#  org.hibernate.type: trace