spring:
  profiles:
    include: oauth
#    active: local

  session:
    store-type: jdbc

  datasource:
    url: jdbc:h2:mem:testdb;MODE=MYSQL
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: false
        format_sql: true
        use_sql_comments: true
        dialect: org.hibernate.dialect.MySQL57Dialect

  data:
    web:
      pageable:
        one-indexed-parameters: true

logging.level:
  org.hibernate.SQL: debug

decorator:
  datasource:
    p6spy:
      enable-logging: false