spring:
  profiles:
    include: oauth
    active: local

  datasource:
    hikari:
      jdbc-url: jdbc:h2:mem:testdb;MODE=MYSQL
      username: sa
      passwrod:
      driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: false
        format_sql: true
        use_sql_comments: true
        dialect: org.hibernate.dialect.MySQL57Dialect

  data:
    web:
      pageable:
        one-indexed-parameters: true

logging.level:
  org.hibernate.SQL: debug


decorator:
  datasource:
    p6spy:
      enable-logging: false