spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/levelupboard
    username: sa
    passwrod:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
#        show_sql: true
        format_sql: true
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect

  profiles:
    include: oauth

logging.level:
  org.hibernate.SQL: debug
#  org.hibernate.type: trace