server:
  port: 8082

spring:
  profiles:
    include:
      - oauth
      - real-db

  session:
    store-type: jdbc

  jpa:
    properties:
      hibernate:
        show_sql: false
        format_sql: true
        use_sql_comments: false

  data:
    web:
      pageable:
        one-indexed-parameters: true

logging.level:
  org.hibernate.SQL: debug

decorator:
  datasource:
    p6spy:
      enable-logging: false